### PR TITLE
More realistic starting point for C++ project

### PR DESCRIPTION
**Pull request by selavy**
C++ is hard enough to get started with unit testing so this change
adds the CMake build system and CppUnit.  There are arguably better unit
testing frameworks (e.g. googletest), but CppUnit is typical of a
legacy project (if they have tests at all).

The project is split into Cpp/src/ and Cpp/include/ directories to simulate a
real library.

The unit test binary is placed at Cpp/bin/tests.

The build is cross platform because it uses CMake.  The general build
instructions are:

[in the Racing-Car-Katas/Cpp directory] (Using Makefiles)
mkdir build
cd build
cmake ..
make

To generate files for different platform, replace "cmake .." with
Visual Studio: "cmake -G "Visual Studio 12" .."
XCode: "cmake -GXCode .."
Ninja: "cmake -GNinja .."
etc.

### CODE REVIEW

**Comment by selavy** [comment]
Hopefully you don't consider this too much help in getting started.  I was looking at this project tonight, and the amount of work just to get started in C++ is non-trivial.

**Comment by emilybache** [comment]
Hi,

I really appreciate you doing something to help C++ programmers to get going quickly with the interesting part of this Kata.  I notice you've added a starting-off test for the Sensor class. I wonder if you could remove that? For this exercise, it's only the Alarm that you're supposed to write tests for.

Thanks.

**Comment by selavy** [comment]
Sensor test remove. Fixed an issue with the CppUnit portion of the CMake and added a README to explain how to build.

**Comment by emilybache** [comment]
Thankyou!

**Pull request merged**
